controller_manager:
  ros__parameters:
    update_rate: 200

    # ROS 2 control broadcasters
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    force_torque_broadcaster:
      type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster

    # LBR ROS 2 control broadcasters
    lbr_state_broadcaster:
      type: lbr_ros2_control/LBRStateBroadcaster

    # ROS 2 control controllers
    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    forward_position_controller:
      type: position_controllers/JointGroupPositionController

    # LBR ROS 2 control controllers
    lbr_joint_position_command_controller:
      type: lbr_ros2_control/LBRJointPositionCommandController

    lbr_torque_command_controller:
      type: lbr_ros2_control/LBRTorqueCommandController

    lbr_wrench_command_controller:
      type: lbr_ros2_control/LBRWrenchCommandController

    # Admittance controller
    admittance_controller:
      type: lbr_ros2_control/AdmittanceController

force_torque_broadcaster:
  ros__parameters:
    frame_id: link_ee # namespace: https://github.com/ros2/rviz/issues/1103
    sensor_name: estimated_ft_sensor

joint_trajectory_controller:
  ros__parameters:
    joints:
      - A1
      - A2
      - A3
      - A4
      - A5
      - A6
      - A7
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    # state_publish_rate: 50.0
    # action_monitor_rate: 20.0
    # gains:
    #   A1:
    #     p: 10.0
    #     i: 0.0
    #     d: 0.0
    #     i_clamp: 0.0
    #     ff_velocity_scale: 1.0
    #   A2:
    #     p: 10.0
    #     i: 0.0
    #     d: 0.0
    #     i_clamp: 0.0
    #     ff_velocity_scale: 1.0      
    #   A3:
    #     p: 10.0
    #     i: 0.0
    #     d: 0.0
    #     i_clamp: 0.0
    #     ff_velocity_scale: 1.0
    #   A4:
    #     p: 10.0
    #     i: 0.0
    #     d: 0.0
    #     i_clamp: 0.0
    #     ff_velocity_scale: 1.0
    #   A5:
    #     p: 10.0
    #     i: 0.0
    #     d: 0.0
    #     i_clamp: 0.0
    #     ff_velocity_scale: 1.0      
    #   A6:
    #     p: 10.0
    #     i: 0.0
    #     d: 0.0
    #     i_clamp: 0.0
    #     ff_velocity_scale: 1.0
    #   A7:
    #     p: 10.0
    #     i: 0.0
    #     d: 0.0
    #     i_clamp: 0.0
    #     ff_velocity_scale: 1.0

forward_position_controller:
  ros__parameters:
    joints:
      - A1
      - A2
      - A3
      - A4
      - A5
      - A6
      - A7
    interface_name: position

